### ISSUE TITLE
Failed to get mobile number because of 'Attempt to invoke virtual method 'java.lang.Object android.app.Activity.getSystemService(java.lang.String)' on a null object reference'

### ISSUE THREAD

**Issue by joshuakoh1** [amorenew/Flutter-Mobile-Number-Plugin#16]
I am able to obtain number when I use it within the main app function as per the example. 

Problem happens when I try to read the mobile number within an isolate started with foreground_service plugin.

```
void maybeStartFGS() async {
  if (!(await ForegroundService.foregroundServiceIsStarted())) {
    await ForegroundService.setServiceIntervalSeconds(5);
    await ForegroundService.startForegroundService(foregroundServiceFunction);
    await ForegroundService.getWakeLock();
  }
}
void foregroundServiceFunction() {
  getMobileNumber();
  ...
}
void getMobileNumber() async{
  try {
    List<mobileNumber.SimCard> cards = await mobileNumber.MobileNumber.getSimCards;
    print(cards);
  } on PlatformException catch (e) {
    debugPrint("Failed to get mobile number because of '${e.message}'");
  }
}
```

```
E/MethodChannel#mobile_number( 2065): Failed to handle method call
E/MethodChannel#mobile_number( 2065): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.app.Activity.getSystemService(java.lang.String)' on a null object reference
E/MethodChannel#mobile_number( 2065):   at com.amorenew.mobile_number.MobileNumberPlugin.getSubscriptions(MobileNumberPlugin.java:214)
E/MethodChannel#mobile_number( 2065):   at com.amorenew.mobile_number.MobileNumberPlugin.generateMobileNumber(MobileNumberPlugin.java:180)
E/MethodChannel#mobile_number( 2065):   at com.amorenew.mobile_number.MobileNumberPlugin.getMobileNumber(MobileNumberPlugin.java:171)
E/MethodChannel#mobile_number( 2065):   at com.amorenew.mobile_number.MobileNumberPlugin.onMethodCall(MobileNumberPlugin.java:121)
E/MethodChannel#mobile_number( 2065):   at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:230)
E/MethodChannel#mobile_number( 2065):   at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#mobile_number( 2065):   at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/MethodChannel#mobile_number( 2065):   at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#mobile_number( 2065):   at android.os.MessageQueue.next(MessageQueue.java:363)
E/MethodChannel#mobile_number( 2065):   at android.os.Looper.loop(Looper.java:176)
E/MethodChannel#mobile_number( 2065):   at android.app.ActivityThread.main(ActivityThread.java:8347)
E/MethodChannel#mobile_number( 2065):   at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#mobile_number( 2065):   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/MethodChannel#mobile_number( 2065):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
```

**Comment by amorenew** [comment]
@joshuakoh1 The plugin is required activity context so I wonder why you need it in the background?

**Comment by joshuakoh1** [comment]
I have incoming SMS listener which has to run in background but it only says which SIM it's received by so I need to fetch the mobile number.

**Comment by amorenew** [comment]
@joshuakoh1 Phone number is for your device sim card so it will never change
So Fetch it and store it before going to background

**Comment by joshuakoh1** [comment]
I considered that but there are cases when SIM card is swapped. There is no trigger to refresh phone number in that case

**Comment by amorenew** [comment]
@joshuakoh1 Either you search for converting my plugin to a service or Just assume swapping SIM cards is not common UX
